site_name: Genotype Blocking Compressor (GBC)
site_description: 基因型数据分块压缩器
site_author: Suranyi
site_url: https://pmglab.top/gbc/

theme:
  name: readthedocs
  feature:
    tabs: true
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  language: 'zh'

# 本地调试端口
dev_addr: 127.0.0.1:4050

extra_javascript:
    - 'js/extra.js'
    - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'

markdown_extensions:
  - mdx_math
  - admonition
  - codehilite:
      guess_lang: true
      linenums: true
  - toc:
      permalink: true
  - footnotes
  - meta
  - def_list
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_png
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist
  - pymdownx.tilde

nav:
  - 中文介绍:
    - 简介: cn/I.简介.md
    - 安装和配置运行环境: cn/II.安装和配置运行环境.md
    - 使用GBC处理基因型数据: cn/III.使用GBC处理基因型数据.md
    - 命令行交互模式: cn/IV.命令行交互模式.md
    - API文档: cn/V.API文档.md